name: rust_lib_ecoblock_mobile
description: "Utility to build Rust code"
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  flutter_reactive_ble: ^5.4.0
  permission_handler: ^12.0.1
  flutter_ble_peripheral: ^1.2.6
  uuid: ^4.5.1
  cupertino_icons: ^1.0.8
  flutter_rust_bridge: 2.11.1
  reactive_ble_mobile: ^5.4.0
  flutter_riverpod: ^2.4.0
  hooks_riverpod: ^2.4.0
  go_router: ^13.2.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10
  shared_preferences: ^2.2.2
  rive: ^0.13.20
  path_provider: ^2.1.5
  flutter_feather_icons: 2.0.0




dev_dependencies:
  ffi: ^2.0.2
  ffigen: ^11.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      windows:
        ffiPlugin: true


  assets:
    - assets/rive/tree.riv